name: do-something
on: push
jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World
        run: echo "Hello, World!"
  hello-world-2:
    name: Hello World 2
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World 2
        run: echo "Hello, World 2!"
